# Generated by Django 2.1.4 on 2019-01-26 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
