# Generated by Django 2.1.4 on 2019-01-27 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_list_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
