# Generated by Django 2.1.4 on 2019-01-27 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_list_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
