# Generated by Django 2.1.4 on 2019-01-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190127_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='due',
        ),
    ]
